import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/header'


export default function Home () {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hogwarts School Brochure</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Hogwarts School of Witchcraft and Wizardry
        </h1>

      </main>
    </div>
  )
}
